const state = {
	category: {
		cakes: [
			{
				id: 1,
				image: 'img/products/cakes/1.jpg',
				name: 'Souffle cake with blueberries',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 2,
				image: 'img/products/cakes/2.jpg',
				name: 'Chocolate cake',
				description: 'who snapped up on the Swiss meringue.',
				price: 30,
			},
			{
				id: 3,
				image: 'img/products/cakes/3.jpg',
				name: 'Biscuit cake with berry filling',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 4,
				image: 'img/products/cakes/4.jpg',
				name: 'Strawberry Cake',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 5,
				image: 'img/products/cakes/5.jpg',
				name: 'Cake with figs',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 6,
				image: 'img/products/cakes/6.jpg',
				name: 'Raspberry and strawberry cake',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 7,
				image: 'img/products/cakes/7.jpg',
				name: 'Yogurt and berry cake',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 8,
				image: 'img/products/cakes/8.jpg',
				name: 'Chocolate berry cake',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 9,
				image: 'img/products/cakes/9.jpg',
				name: 'Cake with apricot filling and oreo cookies',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 10,
				image: 'img/products/cakes/10.jpg',
				name: "Author's cake with exotic fruits",
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 11,
				image: 'img/products/cakes/11.jpg',
				name: 'The souffle cake is decorated with berries and cookies',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 12,
				image: 'img/products/cakes/12.jpg',
				name: 'Classic napoleon decorated with seasonal berries',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
		],
		cupcakes: [
			{
				id: 1,
				image: 'img/products/cupcakes/1.jpg',
				name: 'Blueberry cupcake',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 2,
				image: 'img/products/cupcakes/2.jpg',
				name: 'Creamy cupcake with berries',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 3,
				image: 'img/products/cupcakes/3.jpg',
				name: 'Chocolate cupcake',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 4,
				image: 'img/products/cupcakes/4.jpg',
				name: 'Cupcake with strawberries and chocolate',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 5,
				image: 'img/products/cupcakes/5.jpg',
				name: 'Caramel cupcake with chocolate crumbs',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 6,
				image: 'img/products/cupcakes/6.jpg',
				name: 'Cupcake with nuts',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 7,
				image: 'img/products/cupcakes/7.jpg',
				name: 'Banana cupcake',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 8,
				image: 'img/products/cupcakes/8.jpg',
				name: 'Cupcake with blackberries',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 9,
				image: 'img/products/cupcakes/9.jpg',
				name: 'Cupcake with raspberries',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 10,
				image: 'img/products/cupcakes/10.jpg',
				name: 'Cupcake with strawberries',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 11,
				image: 'img/products/cupcakes/11.jpg',
				name: 'Red cupcake with jam',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 12,
				image: 'img/products/cupcakes/12.jpg',
				name: 'Lemon and grape cupcake',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 13,
				image: 'img/products/cupcakes/13.jpg',
				name: 'Lemon cupcake',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 14,
				image: 'img/products/cupcakes/14.jpg',
				name: 'Easter cupcake',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 15,
				image: 'img/products/cupcakes/15.jpg',
				name: "Cracked raspberry for Valentine's Day",
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 16,
				image: 'img/products/cupcakes/16.jpg',
				name: 'Lavender cupcake',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 17,
				image: 'img/products/cupcakes/17.jpg',
				name: 'Creamy cupcakes',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 18,
				image: 'img/products/cupcakes/18.jpg',
				name: 'Delicate cream cups with strawberries',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 19,
				image: 'img/products/cupcakes/19.jpg',
				name: 'Cupcakes in the form of snowflakes for Christmas',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 20,
				image: 'img/products/cupcakes/20.jpg',
				name: 'Cupcakes with blueberry and lemon cream',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 21,
				image: 'img/products/cupcakes/21.jpg',
				name: 'The yellow cupcake is decorated with slices of lemon',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 22,
				image: 'img/products/cupcakes/22.jpg',
				name: 'Apricot cupcakes',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 23,
				image: 'img/products/cupcakes/23.jpg',
				name: 'Cupcakes with cookies crumbs',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 24,
				image: 'img/products/cupcakes/24.jpg',
				name: 'Oreo cupcakes',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 25,
				image: 'img/products/cupcakes/25.jpg',
				name: 'Green cupcakes are decorated with raspberries and mint',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 26,
				image: 'img/products/cupcakes/26.jpg',
				name: 'Cupcakes with peaches',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 27,
				image: 'img/products/cupcakes/27.jpg',
				name: 'Cupcakes with sugar butterflies',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 28,
				image: 'img/products/cupcakes/28.jpg',
				name: 'Cupcakes for the little princess',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 29,
				image: 'img/products/cupcakes/29.jpg',
				name: 'Chocolate caramel cupcakes',
				description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
		],
		macaroons: [
			{
				id: 1,
				image: 'img/products/macaroons/1.jpg',
				name: 'Macaroons mix',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 2,
				image: 'img/products/macaroons/2.jpg',
				name: 'Macaroons with berry',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 3,
				image: 'img/products/macaroons/3.jpg',
				name: 'Macaroons blue',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 4,
				image: 'img/products/macaroons/4.jpg',
				name: 'Macaroons with blueberries',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 5,
				image: 'img/products/macaroons/5.jpg',
				name: 'Macaroons violets',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 6,
				image: 'img/products/macaroons/6.jpg',
				name: 'Macaroons bead',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 7,
				image: 'img/products/macaroons/7.jpg',
				name: 'Macaroons pink rose',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 8,
				image: 'img/products/macaroons/8.jpg',
				name: 'Macaroons red rose',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 9,
				image: 'img/products/macaroons/9.jpg',
				name: 'Macaroons flower',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 10,
				image: 'img/products/macaroons/10.jpg',
				name: 'Macaroni lavender',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 11,
				image: 'img/products/macaroons/11.jpg',
				name: 'Macaroons green',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 12,
				image: 'img/products/macaroons/12.jpg',
				name: 'Macaroons lilac',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 13,
				image: 'img/products/macaroons/13.jpg',
				name: 'Macaroons raspberry',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 14,
				image: 'img/products/macaroons/14.jpg',
				name: 'Macaroons blueberry',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 15,
				image: 'img/products/macaroons/15.jpg',
				name: 'Macaroons Chinese rose',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 16,
				image: 'img/products/macaroons/16.jpg',
				name: 'Macaroons chocolate',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 17,
				image: 'img/products/macaroons/17.jpg',
				name: 'Macaroons pink',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 18,
				image: 'img/products/macaroons/18.jpg',
				name: 'Macaroons lemon and lime',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 19,
				image: 'img/products/macaroons/19.jpg',
				name: 'Macaroons mandarin',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 20,
				image: 'img/products/macaroons/20.jpg',
				name: 'Macaroons for Christmas',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 21,
				image: 'img/products/macaroons/21.jpg',
				name: 'Macaroons snowman',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 22,
				image: 'img/products/macaroons/22.jpg',
				name: 'Macaroni mint and chocolate',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 23,
				image: 'img/products/macaroons/23.jpg',
				name: 'Macaroons lavender and rose',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 24,
				image: 'img/products/macaroons/24.jpg',
				name: 'Macaroons strawberries with cream',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 25,
				image: 'img/products/macaroons/25.jpg',
				name: 'Macaroni cactus',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 26,
				image: 'img/products/macaroons/26.jpg',
				name: 'Macaroons cactus with flower',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 27,
				image: 'img/products/macaroons/27.jpg',
				name: 'Macaroons multicolored',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 28,
				image: 'img/products/macaroons/28.jpg',
				name: 'Macaroons bubble gum',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 29,
				image: 'img/products/macaroons/29.jpg',
				name: 'Macaroons apple',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
		],
		cookies: [
			{
				id: 1,
				image: 'img/products/cookies/1.jpg',
				name: 'Cookies chocolate and caramel',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 2,
				image: 'img/products/cookies/2.jpg',
				name: 'Cookies dark chocolate',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 3,
				image: 'img/products/cookies/3.jpg',
				name: 'Cookies caramel',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 4,
				image: 'img/products/cookies/4.jpg',
				name: 'Cookies nuts',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 6,
				image: 'img/products/cookies/6.jpg',
				name: 'Cookies sponge',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 7,
				image: 'img/products/cookies/7.jpg',
				name: 'Cookies cream bunnies',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 8,
				image: 'img/products/cookies/8.jpg',
				name: 'Cookies blue bunnies',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 9,
				image: 'img/products/cookies/9.jpg',
				name: 'Cookies pink bunnies',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 10,
				image: 'img/products/cookies/10.jpg',
				name: 'Cookies white bunnies',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 11,
				image: 'img/products/cookies/11.jpg',
				name: 'Cookies Christmas tree with beads',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 12,
				image: 'img/products/cookies/12.jpg',
				name: 'Cookies Christmas tree',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 13,
				image: 'img/products/cookies/13.jpg',
				name: 'Cookies white and blue snowflakes',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 14,
				image: 'img/products/cookies/14.jpg',
				name: 'Cookies Christmas snowflakes',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 15,
				image: 'img/products/cookies/15.jpg',
				name: 'Cookies white hearts',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 16,
				image: 'img/products/cookies/16.jpg',
				name: 'Cookies pink hearts',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 17,
				image: 'img/products/cookies/17.jpg',
				name: 'Cookies heart with roses',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 18,
				image: 'img/products/cookies/18.jpg',
				name: 'Cookies ice cream',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 19,
				image: 'img/products/cookies/19.jpg',
				name: 'Cookies holiday solar',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 20,
				image: 'img/products/cookies/20.jpg',
				name: 'Cookies raisin',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 21,
				image: 'img/products/cookies/21.jpg',
				name: 'Cookies for a birthday',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 22,
				image: 'img/products/cookies/22.jpg',
				name: 'Cookies the elephant',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 23,
				image: 'img/products/cookies/23.jpg',
				name: 'Cookies fruits',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 24,
				image: 'img/products/cookies/24.jpg',
				name: 'Cookies holiday flowers',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 25,
				image: 'img/products/cookies/25.jpg',
				name: "Cookies women's Day",
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 26,
				image: 'img/products/cookies/26.jpg',
				name: 'Cookies wildflowers',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 27,
				image: 'img/products/cookies/27.jpg',
				name: 'Cookies unicorn stars',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 28,
				image: 'img/products/cookies/28.jpg',
				name: 'Cookies yellow candy',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 29,
				image: 'img/products/cookies/29.jpg',
				name: 'Cookies trolls (cartoon characters)',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
			{
				id: 30,
				image: 'img/products/cookies/30.jpg',
				name: 'Cookies orange ice cream',
				description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
				price: 30,
			},
		]
	}

}
export default state