//
// const	cakes = [
// 	{
// 		id: 1,
// 		image: 'img/cakes/1.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 2,
// 		image: 'img/cakes/2.jpg',
// 		name: 'Chocolate cake',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 3,
// 		image: 'img/cakes/3.jpg',
// 		name: 'Biscuit cake with berry filling',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 4,
// 		image: 'img/cakes/4.jpg',
// 		name: 'Strawberry Cake',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 5,
// 		image: 'img/cakes/5.jpg',
// 		name: 'Cake with figs',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 6,
// 		image: 'img/cakes/6.jpg',
// 		name: 'Raspberry and strawberry cake',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 7,
// 		image: 'img/cakes/7.jpg',
// 		name: 'Yogurt and berry cake',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 8,
// 		image: 'img/cakes/8.jpg',
// 		name: 'Chocolate berry cake',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 9,
// 		image: 'img/cakes/9.jpg',
// 		name: 'Cake with apricot filling and oreo cookies',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 10,
// 		image: 'img/cakes/10.jpg',
// 		name: "Author's cake with exotic fruits",
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 11,
// 		image: 'img/cakes/11.jpg',
// 		name: 'The souffle cake is decorated with berries and cookies',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 12,
// 		image: 'img/cakes/cupcakeImg.jpg',
// 		name: 'Classic napoleon decorated with seasonal berries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// ]
//
// const cupcakes = [
// 	{
// 		id: 1,
// 		image: 'img/cupcakes/1.jpg',
// 		name: 'Blueberry cupcake',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 2,
// 		image: 'img/cupcakes/2.jpg',
// 		name: 'Creamy cupcake with berries',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 3,
// 		image: 'img/cupcakes/3.jpg',
// 		name: 'Chocolate cupcake',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 4,
// 		image: 'img/cupcakes/4.jpg',
// 		name: 'Cupcake with strawberries and chocolate',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 5,
// 		image: 'img/cupcakes/5.jpg',
// 		name: 'Caramel cupcake with chocolate crumbs',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 6,
// 		image: 'img/cupcakes/6.jpg',
// 		name: 'Cupcake with nuts',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 7,
// 		image: 'img/cupcakes/7.jpg',
// 		name: 'Banana cupcake',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 8,
// 		image: 'img/cupcakes/8.jpg',
// 		name: 'Cupcake with blackberries',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 9,
// 		image: 'img/cupcakes/9.jpg',
// 		name: 'Cupcake with raspberries',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 10,
// 		image: 'img/cupcakes/10.jpg',
// 		name: 'Cupcake with strawberries',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 11,
// 		image: 'img/cupcakes/11.jpg',
// 		name: 'Red cupcake with jam',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 12,
// 		image: 'img/cupcakes/cupcakeImg.jpg',
// 		name: 'Lemon and grape cupcake',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 13,
// 		image: 'img/cupcakes/13.jpg',
// 		name: 'Lemon cupcake',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 14,
// 		image: 'img/cupcakes/14.jpg',
// 		name: 'Easter cupcake',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 15,
// 		image: 'img/cupcakes/15.jpg',
// 		name: 'Cracked raspberry for Valentine\'s Day',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 16,
// 		image: 'img/cupcakes/16.jpg',
// 		name: 'Lavender cupcake',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 17,
// 		image: 'img/cupcakes/17.jpg',
// 		name: 'Creamy cupcakes',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 18,
// 		image: 'img/cupcakes/18.jpg',
// 		name: 'Delicate cream cups with strawberries',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 19,
// 		image: 'img/cupcakes/19.jpg',
// 		name: 'Cupcakes in the form of snowflakes for Christmas',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 20,
// 		image: 'img/cupcakes/20.jpg',
// 		name: 'Cupcakes with blueberry and lemon cream',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 21,
// 		image: 'img/cupcakes/21.jpg',
// 		name: 'The yellow cupcake is decorated with slices of lemon',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 22,
// 		image: 'img/cupcakes/22.jpg',
// 		name: 'Apricot cupcakes',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 23,
// 		image: 'img/cupcakes/23.jpg',
// 		name: 'Cupcakes with cookies crumbs',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 24,
// 		image: 'img/cupcakes/24.jpg',
// 		name: 'Oreo cupcakes',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 25,
// 		image: 'img/cupcakes/25.jpg',
// 		name: 'Green cupcakes are decorated with raspberries and mint',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 26,
// 		image: 'img/cupcakes/26.jpg',
// 		name: 'Cupcakes with peaches',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 27,
// 		image: 'img/cupcakes/27.jpg',
// 		name: 'Cupcakes with sugar butterflies',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 28,
// 		image: 'img/cupcakes/28.jpg',
// 		name: 'Cupcakes for the little princess',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 29,
// 		image: 'img/cupcakes/29.jpg',
// 		name: 'Chocolate caramel cupcakes',
// 		description: "Weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// ]

// const macaroons = [
// 	{
// 		id: 1,
// 		image: 'img/macaroons/1.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 2,
// 		image: 'img/macaroons/2.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 3,
// 		image: 'img/macaroons/3.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 4,
// 		image: 'img/macaroons/4.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 5,
// 		image: 'img/macaroons/5.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 6,
// 		image: 'img/macaroons/6.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 7,
// 		image: 'img/macaroons/7.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 8,
// 		image: 'img/macaroons/8.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 9,
// 		image: 'img/macaroons/9.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 10,
// 		image: 'img/macaroons/10.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 11,
// 		image: 'img/macaroons/11.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 12,
// 		image: 'img/macaroons/12.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 13,
// 		image: 'img/macaroons/13.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 14,
// 		image: 'img/macaroons/14.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 15,
// 		image: 'img/macaroons/15.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 16,
// 		image: 'img/macaroons/16.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 17,
// 		image: 'img/macaroons/17.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 18,
// 		image: 'img/macaroons/18.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 19,
// 		image: 'img/macaroons/19.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 20,
// 		image: 'img/macaroons/20.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 21,
// 		image: 'img/macaroons/21.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 22,
// 		image: 'img/macaroons/22.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 23,
// 		image: 'img/macaroons/23.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 24,
// 		image: 'img/macaroons/24.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 25,
// 		image: 'img/macaroons/25.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 26,
// 		image: 'img/macaroons/26.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 27,
// 		image: 'img/macaroons/27.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 28,
// 		image: 'img/macaroons/28.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// 	{
// 		id: 29,
// 		image: 'img/macaroons/29.jpg',
// 		name: 'Souffle cake with blueberries',
// 		description: "We discovered the classic message with a saber, weighed the Kurdish recipe for P'Пr Erme, who snapped up on the Swiss meringue.",
// 		price: 30,
// 	},
// ]

// desserts: {
//
// },
