export const IS_LOADING = 'IS_LOADING'
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SHOW_NAVBAR = 'SHOW_NAVBAR'

export const SHOW_AUTH_FORM = 'SHOW_AUTH_FORM'
export const SHOW_REGISTER = 'SHOW_REGISTER'

export const SHOW_AUTH_FORM_SAGA = 'SHOW_AUTH_FORM_SAGA'
export const SHOW_REGISTER_SAGA = 'SHOW_REGISTER_SAGA'

export const POST_NEW_USER = 'POST_NEW_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CHECK_LOGIN_SAGA = 'CHECK_LOGIN_SAGA'
export const LOGOUT_CURRENT_USER_SAGA = 'GET_PRODUCTS_CATEGORY_SAGA'

export const GET_PRODUCTS_CATEGORY_SAGA = 'LOGOUT_CURRENT_USER_SAGA'
export const SET_PRODUCTS_LIST = 'SET_PRODUCTS_LIST'
export const GET_PRODUCTS_SEARCH_SAGA = 'GET_PRODUCTS_SEARCH_SAGA'
export const SET_PRODUCTS_SEARCH_RESULT = 'SET_PRODUCTS_SEARCH_RESULT'

export const ADD_PRICE_TO_BASKET = 'ADD_PRICE_TO_BASKET'
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const BUY_BTN_HANDLER = 'BUY_BTN_HANDLER'
export const BUY_BTN_HANDLER_SAGA = 'BUY_BTN_HANDLER_SAGA'