export const GET_ERRORS = 'GET_ERRORS'
export const USER_LOADING = 'USER_LOADING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const SHOW_SAGA_AUTH_FORM = 'SHOW_SAGA_AUTH_FORM'
export const SHOW_AUTH_FORM = 'SHOW_AUTH_FORM'

export const HIDE_SAGA_AUTH_FORM = 'HIDE_SAGA_AUTH_FORM'
export const HIDE_AUTH_FORM = 'HIDE_AUTH_FORM'

export const SHOW_SAGA_REGISTER = 'SHOW_SAGA_REGISTER'
export const SHOW_REGISTER = 'SHOW_REGISTER'

export const SHOW_SAGA_LOGIN = 'SHOW_SAGA_LOGIN'
export const SHOW_LOGIN = 'SHOW_LOGIN'

export const POST_NEW_USER = 'POST_NEW_USER'